# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily" # Per la NIS 2 è meglio un controllo frequente
    open-pull-requests-limit: 5
    # Abilita gli aggiornamenti di sicurezza automatici
    allow:
      - dependency-type: "all"
